### PR TITLE
Create throttle testing 

### PR DESCRIPTION
**Pull request by Nashtronaut**
## Description

Created testing methods for throttles.

## Changes

- [X] Created test function for throttle. 

## To Do

- [X] Deno lint failing because of `type any` being unspecific in `testPromise()`.

### CODE REVIEW

**Comment by Nashtronaut** [comment]
One question I did have, I understand that `interval` and `limit` are passed into `createThrottle` as parameters but it seems like `throttle()` can be called like an object, is that right? 

It would be nice to set the variables by using `const period = throttle.interval / throttle.limit` instead of `const period = 100 / 3` but I don't think they are set as parameters of the `throttle` object. I'm not entirely sure if this is a thing that can be done.

@MarkBennett what do you think? 

I am specifically referring too https://github.com/burmis/create-throttle/blob/1e419fe4773681f181bde1cc2e70f3b4ba53c2b6/mod_test.ts#L43-L44 and https://github.com/burmis/create-throttle/blob/1e419fe4773681f181bde1cc2e70f3b4ba53c2b6/mod_test.ts#L72

**Comment by MarkBennett** [comment]
> One question I did have, I understand that `interval` and `limit` are passed into `createThrottle` as parameters but it seems like `throttle()` can be called like an object, is that right?
> 
> It would be nice to set the variables by using `const period = throttle.interval / throttle.limit` instead of `const period = 100 / 3` but I don't think they are set as parameters of the `throttle` object. I'm not entirely sure if this is a thing that can be done.
> 
> @MarkBennett what do you think?
> 
> I am specifically referring too
> 
> https://github.com/burmis/create-throttle/blob/1e419fe4773681f181bde1cc2e70f3b4ba53c2b6/mod_test.ts#L43-L44
> 
> and
> https://github.com/burmis/create-throttle/blob/1e419fe4773681f181bde1cc2e70f3b4ba53c2b6/mod_test.ts#L72

Thanks for suggesting this! A few thoughts here @Nashtronaut.

1) I agree that if the throttle is using the `period` internally then it would be useful to expose that rather than calculating again

2) Have you learned about the idea of * "immutability"*? Basically, it's the idea that once you create something you can't change it anymore. Right now, the throttle is immutable since once it's created you can't change the `limit` or `interval` later. Instead you need to create a new throttle if you want to change those values. This keeps reasoning about the throttle simpler, and avoids a lot of complexity and bugs.

With these thoughts in mind, perhaps we just expose the `limit`, `interval` and `period` as read-only properties on the throttle? It's not a common pattern, but you can use Object.defineProprty to expose these as read-only, or with a getter method like this:

```js
/// in `createThrottle()`
const throttleFunc = () => {
    /// snip
};

Object.defineProperty(throttleFunc, 'limit', {
  value: limit,
  writable: false
});


Object.defineProperty(throttleFunc, 'interval', {
  value: interval,
  writable: false
});

Object.defineProperty(throttleFunc, 'period', {
  value: period,
  writable: false
});

return throttleFunc
```

You could then access these on your throttle func but can't set them...

```js
const throttle = createThrottle({ limit: 3, interval: 100});
console.log("period = ", throttle.period);  // 33

throttle.period = 100


console.log("period = ", throttle.period);  // Still = 33
```

I'm fine it you'd like to go ahead and make this change, but don't have a big concern with the code as it stands now. If you'd like to spend 30 minutes on this, that's fine with me.

**Comment by Nashtronaut** [comment]
> 

Since there was no concern, I didn't end up doing the change. I am okay to merge this and close this PR if you are! @MarkBennett

**Review by MarkBennett — APPROVED** [review]
Changes look good and the TS `any` error is gone as well. Nice work @Nashtronaut!

Ship it! 🚢

**Pull request merged**
